/**
 * Callout block save component.
 *
 * This block uses server-side rendering (render.php), so the save function
 * returns null. The frontend markup is generated by render.php.
 *
 * @package ItMogul
 */
import { useBlockProps } from "@wordpress/block-editor";

/**
 * Save component.
 *
 * @return {null} Returns null because the block is server-side rendered.
 */
export default function save() {
    const blockProps = useBlockProps.save();

    return <div {...blockProps} />;
}
